name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select target environment"
        type: choice
        required: true
        options:
          - test
          - int

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest

    # This is the important part
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show selected environment
        run: |
          echo "Deploying to environment: ${{ inputs.environment }}"
          echo "VAR1 ${{ vars.VAR1 }}"


      - name: Deploy
        run: |
          echo "Running deployment for ${{ inputs.environment }}"
          # your deployment logic here
